[env:final]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino
monitor_speed = 115200
board_build.variants_dir = variants
board_build.variant = heltec_V4
lib_deps =
    knolleary/PubSubClient@^2.8.0
    kosme/arduinoFFT@^2.0.4
