[env:fft_average_sender]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -D SENDER_MODE
monitor_dtr = 0
monitor_rts = 0
lib_deps =
	adafruit/Adafruit INA219
