[env:lora]
platform = espressif32
board = heltec_wifi_lora_32_V4
framework = arduino
monitor_speed = 115200
board_build.variants_dir = variants
board_build.variant = heltec_V4
build_flags =
    -DHELTEC_BOARD=39
    -DSLOW_CLK_TPYE=1
    -DLoRaWAN_DEBUG_LEVEL=0
    -DWIFI_LORA_32_V4
    -DUSE_GC1109_PA
    -DRADIO_CHIP_SX1262
    -DGPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT
lib_deps =
    https://github.com/HelTecAutomation/Heltec_ESP32.git
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit BusIO@^1.17.1
